### ISSUE TITLE
Intersection vertex issue

### ISSUE THREAD

**Issue by kintel** [memononen/libtess2#11]
This is more a question than an issue:

I'm feeding a self-intersecting polygon to the tessellator, e.g. an hourglass:
```
0 0 0
1 0 0
0 1 0
1 1 0
```

Now, this will be tessellated into two triangles
[1 0 0], [0 0 0] , [<intersection>]
[1 1 0], [<intersection>], [0 1 0]

I don't generally know which intersection this is and there is no callback to let me calculate it.
I see that the demo program just ignore them.
Since I plan on using this to tessellate manifold meshes, I cannot just leave out triangles as that would destroy the connectivity of my mesh.

Could someone shed some light on this?

**Comment by memononen** [comment]
I'm not sure what you mean. Do you want to know when you get a new vertex from intersection?

**Comment by kintel** [comment]
Yes, libtess2 will create new vertices, but I didn't find a way of getting access to these new vertices. When I first evaluated this I didn't realize that this part of gluTess appears to be removed (it was supplied by gluTess using the combine callback).

In reality, my problem is different, but would probably require a similar function.
FYI: If an intersection occurs, I never want to introduce new vertices; I will fall back to tessellating the intersecting subset of the polygon using another approach. The reason for this is that input polygons may not be 100% planar (due to floating point inaccuracies), intersections may be a result of such inaccuracies and should be ignored as the triangulation may still be valid in 3D space.

**Comment by memononen** [comment]
Ok, now I get it. You can get the input vertex index* as output, new vertices will have `TESS_UNDEF`as index, see the demo here: https://github.com/memononen/libtess2/blob/master/Example/example.c#L299

*the indices are "accumulated" so that if you first add a contour with 12 vertices and then contour with 3 vertices, the second vertex of the second contour will have index of 12+1=13.

**Comment by kintel** [comment]
Ah, thanks, I misunderstood the indexing.
