### ISSUE TITLE
Degenerate Triangle

### ISSUE THREAD

**Issue by bryanmcconkey** [memononen/libtess2#17]
Is it expected that the lib can produce degenerate triangles? I had a case which was giving me a 0,0,0 normal for the first polygon and a degenerate triangle was to blame. This is not a big deal as its easy to process out now that I am aware of this possibility, but I wanted to check in case its considered a bug.

**Comment by memononen** [comment]
Yes, it is possible. For example if you have a tessellated rectangle, the left or right edge may contain degenerate triangles.

**Comment by bryanmcconkey** [comment]
Alright, not a problem. Thanks for confirming. Closing the issue.
