### ISSUE TITLE
assertion when processing a degenerate rectangle

### ISSUE THREAD

**Issue by GrahamAsher** [memononen/libtess2#24]
The assertion is thrown in tesedgeSign:

```
TESSreal tesedgeSign( TESSvertex *u, TESSvertex *v, TESSvertex *w )
{
    /* Returns a number whose sign matches EdgeEval(u,v,w) but which
    * is cheaper to evaluate.  Returns > 0, == 0 , or < 0
    * as v is above, on, or below the edge uw.
    */
    TESSreal gapL, gapR;

    assert( VertLeq( u, v ) && VertLeq( v, w )); // ASSERTION THROWN HERE

    gapL = v->s - u->s;
    gapR = w->s - v->s;

    if( gapL + gapR > 0 ) {
        return (v->t - w->t) * gapL + (v->t - u->t) * gapR;
    }
    /* vertical line */
    return 0;
}
```

in geom.c.

The cause seems to be that it is processing a rectangle where all the x cooordinates are the same (so the rectangle is just a line) and the first and last points are the same:

11333544,13772171
11333544,13772299 
11333544,13772107
11333544,13772171

It would be great if libtess2 could handle degenerate cases gracefully.

**Comment by memononen** [comment]
This is fixed by the most recent changes.
