### ISSUE TITLE
Consultation on release plan

### ISSUE THREAD

**Issue by hietwll** [memononen/libtess2#47]
Dear Sir,

We have used your open source software in a product that is about to be released. Thank you for your generosity and contribution to the community.

Before we officially release our product, we need to evaluate that the open source software used is in its normal lifecycle. We noticed that libtess2 has not been updated for several years. 

I personally know that libtess2 is quite stable and has been widely used in many products (such as flutter, Kanzi, etc.), but for some reason, we still need your formal confirmation that: **libtess2 is mature and stable enough, so there won't be new features, no need for massive bugfix, and no plan for releasing new versions**.

We hope you can provide us with an answer that is clear and concise. If you have any questions, please do not hesitate to contact us.

Thank you for your time and attention.

Best regards,

Wang

**Comment by memononen** [comment]
Hi! Libtess2 is in light support mode, that is, I do not plan to add new features. I merge trivial bug fix PRs if they arrive, but I dot have time to do bug fixing myself.

**Comment by hietwll** [comment]
thanks for reply, problem fixed.
