### ISSUE TITLE
Better triangulation of regions

### ISSUE THREAD

**Issue by kintel** [memononen/libtess2#6]
I notice that after identifying monotone regions, the region is triangulated into a triangle fan using a relatively naive technique. This generates triangles without regard to their aspect ratio, and even tends to generate "zero triangles" (three collinear vertices).
Now, for rendering, this usually not a problem, but for other uses it causes problems, e.g. due to these triangles not having a normal vector and thus don't live in a well-defined plane.

Have you thought about rewriting the triangle fanning code to produce better triangles, or are you interested in accepting such patches?

I realize that for rendering of strips, fanning is more performant than other organizations, but we could make this an option.

**Comment by memononen** [comment]
Hi, the library is a port of the original GLU tessellator, I have kept a lot of the original code intact.

I'd be definitely interested in such patch. I have mostly dealt with ear-clipping type of triangulation in the last, so I dont' have an immediate idea how to improve the triangulation taking the monotone property into account.

**Comment by kintel** [comment]
I believe greedy ear clipping would already improve the triangulation significantly. I'll try to look into it.

FYI: I've been looking for triangulation libraries, and I still haven't found any other open source library as robust as this one. CGAL's constrained delaunay triangulator worked for a while, but I eventually managed to crash it. If the triangulation ends up yielding better triangles, this would have a lot of potential uses.

**Comment by jesusdesantos** [comment]
We would be also interested in that patch. With minor modifications, is the tesselator we are using in noesisGUI.

**Comment by kintel** [comment]
@jesusdesantos See https://github.com/memononen/libtess2/pull/7 - feel free to give it a spin.

**Comment by memononen** [comment]
Merged your CDT code with slight modifications. Thanks for the PR and sorry for one more time for the long wait.
